name: atba_application
description: Flutter Clean Architecture Series
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.0
  ionicons: ^0.2.2

  # Networking
  retrofit: ^3.3.0
  dio: ^4.0.6

  # State Management
  flutter_bloc: ^8.1.2

  # Others
  flutter_hooks: ^0.18.5+1
  get_it: ^7.2.0
  floor: ^1.4.1
  equatable: ^2.0.5
  oktoast: ^3.3.1
  awesome_dio_interceptor: ^0.0.2+4
  auto_route: ^5.0.4
  flutter_animate: ^4.1.1+1
  otp_text_field: ^1.1.3
  persian_number_utility: ^1.1.3
  dotted_line: ^3.1.0
  modal_bottom_sheet:
    git:
      url: https://github.com/bayysp/modal_bottom_sheet.git
      path: modal_bottom_sheet
      ref: 3.0.0-pre+1-idn_version
  persian_datetime_picker: ^2.6.0
  lottie: ^2.3.2
  dio_logging_interceptor: ^1.0.1
  timer_count_down: ^2.2.2
  shared_preferences: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.0.1
  auto_route_generator: ^5.0.3
  retrofit_generator: ^4.1.2
  floor_generator: ^1.4.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/image_icon/
    - assets/loading.json

  fonts:
    - family: Snapp
      fonts:
        - asset: assets/fonts/snapp_font.ttf

    - family: shabnam_bold
      fonts:
        - asset: assets/fonts/shabnam_bold.ttf
