// Mocks generated by Mockito 5.4.0 from annotations
// in atba_application/test/features/feature_login/presentation/block/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:atba_application/core/params/verify_otp_param.dart' as _i9;
import 'package:atba_application/core/resources/data_state.dart' as _i3;
import 'package:atba_application/features/feature_login/domain/entities/send_otp_code_entity.dart'
    as _i6;
import 'package:atba_application/features/feature_login/domain/entities/verify_otp_code_entity.dart'
    as _i8;
import 'package:atba_application/features/feature_login/domain/repository/login_repository.dart'
    as _i2;
import 'package:atba_application/features/feature_login/domain/use_cases/send_otp_code_usecase.dart'
    as _i4;
import 'package:atba_application/features/feature_login/domain/use_cases/verify_otp_code_usecase.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginRepository_0 extends _i1.SmartFake
    implements _i2.LoginRepository {
  _FakeLoginRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataState_1<T> extends _i1.SmartFake implements _i3.DataState<T> {
  _FakeDataState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SendOtpCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendOtpCodeUseCase extends _i1.Mock
    implements _i4.SendOtpCodeUseCase {
  MockSendOtpCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LoginRepository get loginRepository => (super.noSuchMethod(
        Invocation.getter(#loginRepository),
        returnValue: _FakeLoginRepository_0(
          this,
          Invocation.getter(#loginRepository),
        ),
      ) as _i2.LoginRepository);
  @override
  _i5.Future<_i3.DataState<_i6.SendOtpCodeEntity>> call(String? phoneNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [phoneNumber],
        ),
        returnValue: _i5.Future<_i3.DataState<_i6.SendOtpCodeEntity>>.value(
            _FakeDataState_1<_i6.SendOtpCodeEntity>(
          this,
          Invocation.method(
            #call,
            [phoneNumber],
          ),
        )),
      ) as _i5.Future<_i3.DataState<_i6.SendOtpCodeEntity>>);
}

/// A class which mocks [VerifyOtpCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyOtpCodeUseCase extends _i1.Mock
    implements _i7.VerifyOtpCodeUseCase {
  MockVerifyOtpCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LoginRepository get loginRepository => (super.noSuchMethod(
        Invocation.getter(#loginRepository),
        returnValue: _FakeLoginRepository_0(
          this,
          Invocation.getter(#loginRepository),
        ),
      ) as _i2.LoginRepository);
  @override
  _i5.Future<_i3.DataState<_i8.VerifyOtpCodeEntity>> call(
          _i9.VerifyOtpParam? verifyOtpParam) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [verifyOtpParam],
        ),
        returnValue: _i5.Future<_i3.DataState<_i8.VerifyOtpCodeEntity>>.value(
            _FakeDataState_1<_i8.VerifyOtpCodeEntity>(
          this,
          Invocation.method(
            #call,
            [verifyOtpParam],
          ),
        )),
      ) as _i5.Future<_i3.DataState<_i8.VerifyOtpCodeEntity>>);
}
